//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentService.QueryResources", typeof(QueryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT     c.TermCode
        ///	, c.Crn
        ///	, c.Subject
        ///	, c.CourseNumb
        ///	, c.Sequence
        ///	, c.Name
        ///	, s.SectionType
        ///	, s.StartDate
        ///	, s.EndDate
        ///	, s.StartTime
        ///	, s.EndTime
        ///	, s.DaysOfWeek
        ///FROM         
        ///	vCourses c 
        ///	INNER JOIN Sections s
        ///        ON c.TermCode = s.TermCode 
        ///            AND c.Crn = s.Crn
        ///WHERE 
        ///	c.TermCode = @Term 
        ///	AND c.DepartmentId = @Department.
        /// </summary>
        internal static string CourseSectionQuery {
            get {
                return ResourceManager.GetString("CourseSectionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT     c.TermCode
        ///	, c.Crn
        ///	, c.Subject
        ///	, c.CourseNumb
        ///	, c.Sequence
        ///	, c.Name
        ///	, s.SectionType
        ///	, s.StartDate
        ///	, s.EndDate
        ///	, s.StartTime
        ///	, s.EndTime
        ///	, s.DaysOfWeek
        ///FROM         
        ///	vCourses c 
        ///	INNER JOIN Sections s
        ///        ON c.TermCode = s.TermCode 
        ///            AND c.Crn = s.Crn
        ///WHERE 
        ///	c.TermCode = @Term
        ///	AND c.Subject = @Subject
        ///	AND c.CourseNumb in ({0}).
        /// </summary>
        internal static string CoursesSubjectQuery {
            get {
                return ResourceManager.GetString("CoursesSubjectQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT     c.TermCode
        ///	, c.Crn
        ///	, c.Subject
        ///	, c.CourseNumb
        ///	, c.Sequence
        ///	, c.Name
        ///	, s.SectionType
        ///	, s.StartDate
        ///	, s.EndDate
        ///	, s.StartTime
        ///	, s.EndTime
        ///	, s.DaysOfWeek
        ///FROM         
        ///	vCourses c 
        ///	INNER JOIN Sections s
        ///        ON c.TermCode = s.TermCode 
        ///            AND c.Crn = s.Crn
        ///WHERE 
        ///	c.TermCode = @Term
        ///	AND c.Subject = @Subject
        ///	AND c.CourseNumb = @CourseNumb.
        /// </summary>
        internal static string CourseSubjectQuery {
            get {
                return ResourceManager.GetString("CourseSubjectQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id, Name from Departments where Id = @subject.
        /// </summary>
        internal static string DeparmentFindQuery {
            get {
                return ResourceManager.GetString("DeparmentFindQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Departments.Id, Departments.Name from courses
        ///inner join Departments on DepartmentId = Departments.Id
        ///where crn = @crn.
        /// </summary>
        internal static string DepartmentCrnQuery {
            get {
                return ResourceManager.GetString("DepartmentCrnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select s.LoginId
        ///,s.FirstName
        ///,s.LastName
        ///,s.Email
        ///from CourseRoster r
        ///	inner join students s on r.loginid = s.loginid
        ///where 
        ///	r.Termcode =@Term
        ///	AND r.Crn =@Crn
        ///	
        ///select ci.LoginId
        ///,i.FirstName
        ///,i.LastName
        ///,i.Email
        ///from CourseInstructors ci
        ///	inner join Instructors i on ci.loginid = i.loginid
        ///where
        ///	ci.TermCode = @Term
        ///	AND ci.Crn = @Crn.
        /// </summary>
        internal static string RosterQuery {
            get {
                return ResourceManager.GetString("RosterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select s.LoginId
        ///,s.FirstName
        ///,s.LastName
        ///,s.Email
        ///,r.Crn
        ///from CourseRoster r
        ///	inner join vCourses c on (r.Crn = c.Crn AND r.TermCode = c.TermCode)
        ///	inner join students s on r.LoginId = s.LoginId
        ///where 
        ///	r.TermCode = @Term	
        ///	AND c.Subject = @Subject
        ///	AND c.CourseNumb in ({0})
        ///
        ///select i.LoginId
        ///,i.FirstName
        ///,i.LastName
        ///,i.Email
        ///,c.Crn
        ///from CourseInstructors ci
        ///	inner join vCourses c on (ci.Crn = c.Crn AND ci.TermCode = c.TermCode)
        ///	inner join Instructors i on ci.LoginId = i.LoginId
        ///where [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RostersSubjectQuery {
            get {
                return ResourceManager.GetString("RostersSubjectQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select s.LoginId
        ///,s.FirstName
        ///,s.LastName
        ///,s.Email
        ///,r.Crn
        ///from CourseRoster r
        ///	inner join vCourses c on (r.Crn = c.Crn AND r.TermCode = c.TermCode)
        ///	inner join students s on r.LoginId = s.LoginId
        ///where 
        ///	r.TermCode = @Term	
        ///	AND c.Subject = @Subject
        ///	AND c.CourseNumb = @CourseNumb
        ///
        ///select i.LoginId
        ///,i.FirstName
        ///,i.LastName
        ///,i.Email
        ///,c.Crn
        ///from CourseInstructors ci
        ///	inner join vCourses c on (ci.Crn = c.Crn AND ci.TermCode = c.TermCode)
        ///	inner join Instructors i on ci.LoginId = i.LoginId
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RosterSubjectQuery {
            get {
                return ResourceManager.GetString("RosterSubjectQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id]
        ///      ,[Name]
        ///      ,[Start]
        ///      ,[End]
        ///  FROM [TermCodes].
        /// </summary>
        internal static string TermCodeQuery {
            get {
                return ResourceManager.GetString("TermCodeQuery", resourceCulture);
            }
        }
    }
}
